export const Industries = [
  { value: "", label: "View All Jobs" },
  { value: "Aerospace/Aviation", label: "Aerospace/Aviation" },
  { value: "Architecture/Construction", label: "Architecture/Construction" },
  { value: "Audio/Video", label: "Audio/Video" },
  { value: "Business/Management", label: "Business/Management" },
  { value: "Education and Training", label: "Education and Training" },
  { value: "Engineering/Science", label: "Engineering/Science" },
  { value: "Finance", label: "Finance" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Hospitality", label: "Hospitality" },
  { value: "Human Services", label: "Human Services" },
  { value: "Information Technology", label: "Information Technology" },
  { value: "Law Enforcement/Security", label: "Law Enforcement/Security" },
  { value: "Maintenance", label: "Maintenance" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Marketing/Sales", label: "Marketing/Sales" },
  { value: "Transportation/Logistics", label: "Transportation/Logistics" },

  { value: "Tradesman", lable: "Tradesman" },
];

export const featuredJobListings = [
  {
    "web-scraper-order": "1704823057-3",
    "web-scraper-start-url":
      "https://rtt-jv.hua.hrsmart.com/hr/ats/JobSearch/viewAll",
    jobLink: "Master Machinist (CNC)",
    "jobLink-href": "https://rtt-jv.hua.hrsmart.com/hr/ats/Posting/view/1038",
    jobTitle: "Master Machinist",
    numberOfPositions: 1,
    clearanceRequired: "Secret",
    workLocation: "TS C-64 (Crestview) FL",
    jobType: "Full-time",
    salaryType: "Non-Exempt",
    education: "Industry Certification",
    careerLevel: "Master",
    jobCategory: "Trades",
    hourlyPay: 30.22,
    jobNameClean: "",
    positionNumber: "Open Position Request Number R-101-23",
    experienceRequired:
    "Secret clearance, machine shop, CNC machine, 10 years experience, MIG and TIG tack weld, silver solder, sheet metal.",
  },
];

export const jobListings = [
  {
    "web-scraper-order": "1704823057-2",
    "web-scraper-start-url":
      "https://rtt-jv.hua.hrsmart.com/hr/ats/JobSearch/viewAll",
    jobLink: "Master Machinist (CNC)",
    "jobLink-href": "https://rtt-jv.hua.hrsmart.com/hr/ats/Posting/view/1038",
    jobTitle: "Master Machinist (CNC)",
    numberOfPositions: 1,
    clearanceRequired: "Secret",
    workLocation: "TS C-64 (Crestview) FL",
    jobType: "Full-time",
    salaryType: "Non-Exempt",
    education: "Industry Certification",
    careerLevel: "Master",
    jobCategory: "Trades",
    hourlyPay: 30.22,
    jobNameClean: "",
    positionNumber: "Open Position Request Number R-101-23",
    experienceRequired:
      "Secret clearance, CNC machine operation, shop mathematics, independent judgements, complex parts.",
  },
  {
    "web-scraper-order": "1704823059-5",
    "web-scraper-start-url":
      "https://rtt-jv.hua.hrsmart.com/hr/ats/JobSearch/viewAll",
    jobLink: "Contract Support Specialist",
    "jobLink-href": "https://rtt-jv.hua.hrsmart.com/hr/ats/Posting/view/1000",
    jobTitle: "Contract Support Specialist",
    numberOfPositions: 1,
    clearanceRequired: "Secret",
    workLocation: "Eglin AFB",
    jobType: "Full-time",
    salaryType: "Exempt",
    education: "Bachelor's Degree",
    careerLevel: "Experienced (Non-Manager)",
    jobCategory: "Administrative/Clerical",
    hourlyPay: "50-55k",
    jobNameClean: "",
    positionNumber: "",
    experienceRequired:
"Secret clearance, contract management, procurement, government interactions, technical directives, cost estimates, contract data requirements lists, scope of contract.",
  },
  {
    "web-scraper-order": "1704823062-8",
    "web-scraper-start-url":
      "https://rtt-jv.hua.hrsmart.com/hr/ats/JobSearch/viewAll",
    jobLink: "Electrician, Apprentice",
    "jobLink-href": "https://rtt-jv.hua.hrsmart.com/hr/ats/Posting/view/1031",
    jobTitle: "Electrician, Apprentice",
    numberOfPositions: 1,
    clearanceRequired: "Secret",
    workLocation: "Eglin AFB, FL",
    jobType: "Full-time",
    salaryType: "Non-Exempt",
    education: "Some College Coursework Completed",
    careerLevel: "Student",
    jobCategory: "Trades",
    hourlyPay: 18.54,
    jobNameClean: "",
    positionNumber: "",
    experienceRequired:
      "Secret clearance, installation, maintenance, repair, on-the-job training.",
  },
  {
    "web-scraper-order": "1704823064-10",
    "web-scraper-start-url":
      "https://rtt-jv.hua.hrsmart.com/hr/ats/JobSearch/viewAll",
    jobLink: "Welder, Apprentice",
    "jobLink-href": "https://rtt-jv.hua.hrsmart.com/hr/ats/Posting/view/1053",
    jobTitle: "Welder, Apprentice",
    numberOfPositions: 1,
    clearanceRequired: "Secret",
    workLocation: "Eglin AFB, FL",
    jobType: "Full-time",
    salaryType: "Non-Exempt",
    education: "High School Diploma / GED",
    careerLevel: "Entry Level",
    jobCategory: "Trades",
    hourlyPay: 18.78,
    jobNameClean: "",
    positionNumber: "",
    experienceRequired:
      "Secret clearance, high school graduate, welding, piping systems, pressure vessels.",
  },
];
