export const Industries = [
  { value: '', label: 'View All Jobs'},
  { value: 'Aerospace/Aviation', label: 'Aerospace/Aviation'},
  { value: 'Architecture/Construction', label: 'Architecture/Construction'},
  { value: 'Audio/Video', label: 'Audio/Video'},
  { value: 'Business/Management', label: 'Business/Management'},
  { value: 'Education and Training', label: 'Education and Training'},
  { value: 'Engineering/Science', label: 'Engineering/Science'},
  { value: 'Finance', label: 'Finance'},
  { value: 'Healthcare', label: 'Healthcare'},
  { value: 'Hospitality', label: 'Hospitality'},
  { value: 'Human Services', label: 'Human Services'},
  { value: 'Information Technology', label: 'Information Technology'},
  { value: 'Law Enforcement/Security', label: 'Law Enforcement/Security'},
  { value: 'Maintenance', label: 'Maintenance'},
  { value: 'Manufacturing', label: 'Manufacturing'},
  { value: 'Marketing/Sales', label: 'Marketing/Sales'},
  { value: 'Transportation/Logistics', label: 'Transportation/Logistics'},

  { value: 'Tradesman', lable: 'Tradesman'}
];

// export const jobListings = [
//   { id: '20240108-001',
//     industry: 'Tradesman',
//     jobTitle: 'Master Machinist',
//     clearanceRequired: 'Top Secret',
//     salaryMinimum: 85000,
//     salaryMaximum: 1250000,
//     jobRequirements: 'Machine shop, CNC machine, 10 years experience, MIG and TIG tack weld, silver solder, and sheet metal.',
//   },
//   { id: '20240108-002',
//   industry: 'Tradesman',
//   jobTitle: 'Master Machinist',
//   clearanceRequired: 'Top Secret',
//   salaryMinimum: 85000,
//   salaryMaximum: 1250000,
//   jobRequirements: 'Incumbents must have either: formal training in machine shop practices and CNC machine operations acquired through vocational or military service school training or a machinist apprenticeship program and 10 years’ experience in the machinist trade, of which 5 years on the E-OMS contract or 15 years’ experience in the machinist trade of which 5 years on the E-OMS contract.  Must be able to MIG and TIG tack weld, silver solder, and work with sheet metal.',
// },
// { id: '20240108-003',
// industry: 'Tradesman',
// jobTitle: 'Master Machinist',
// clearanceRequired: 'Top Secret',
// salaryMinimum: 85000,
// salaryMaximum: 1250000,
// jobRequirements: 'Incumbents must have either: formal training in machine shop practices and CNC machine operations acquired through vocational or military service school training or a machinist apprenticeship program and 10 years’ experience in the machinist trade, of which 5 years on the E-OMS contract or 15 years’ experience in the machinist trade of which 5 years on the E-OMS contract.  Must be able to MIG and TIG tack weld, silver solder, and work with sheet metal.',
// },
// { id: '20240108-004',
// industry: 'Tradesman',
// jobTitle: 'Master Machinist',
// clearanceRequired: 'Top Secret',
// salaryMinimum: 85000,
// salaryMaximum: 1250000,
// jobRequirements: 'Incumbents must have either: formal training in machine shop practices and CNC machine operations acquired through vocational or military service school training or a machinist apprenticeship program and 10 years’ experience in the machinist trade, of which 5 years on the E-OMS contract or 15 years’ experience in the machinist trade of which 5 years on the E-OMS contract.  Must be able to MIG and TIG tack weld, silver solder, and work with sheet metal.',
// }
// ];

export const MinimumSalary = [
  { value: '', label: 'Select Minimum Salary:'},
  { value: '40', label: '$40,000'},
  { value: '50', label: '$50,000'},
  { value: '60', label: '$60,000'},
  { value: '70', label: '$70,000'},
  { value: '80', label: '$80,000'},
  { value: '90', label: '$90,000'},
  { value: '100', label: '$100,000'},
  { value: '110', label: '$110,000'},
  { value: '120', label: '$120,000'},
  { value: '130', label: '$130,000'},
  { value: '140', label: '$140,000'},
  { value: '150', label: '$150,000'},
];

export const MaximumSalary = [
  { value: '', label: 'Select Maximum Salary:'},
  { value: '50', label: '$50,000'},
  { value: '60', label: '$60,000'},
  { value: '70', label: '$70,000'},
  { value: '80', label: '$80,000'},
  { value: '90', label: '$90,000'},
  { value: '100', label: '$100,000'},
  { value: '110', label: '$110,000'},
  { value: '120', label: '$120,000'},
  { value: '130', label: '$130,000'},
  { value: '140', label: '$140,000'},
  { value: '150', label: '$150,000'},
  { value: '160', label: '$160,000'},
  { value: '170', label: '$170,000'},
  { value: '180', label: '$180,000'},
  { value: '190', label: '$190,000'},
  { value: '200', label: '$200,000'},
  { value: '210', label: '$210,000'},
  { value: '220', label: '$220,000'},
  { value: '230', label: '$230,000'},
];

export const MinimumTimeOff = [
  { value: '', label: 'Select Minimum PTO:'},
  { value: '40', label: '40 Hours'},
  { value: '80', label: '80 Hours'},
  { value: '120', label: '120 Hours'},
  { value: '160', label: '160 Hours'},
  { value: '200', label: '200 Hours'},
  { value: '240', label: '240 Hours'},
  { value: '280', label: '280 Hours'},
];

export const Matching401k = [
  { value: '', label: 'Select Maximum 401k:'},
  { value: '1', label: '1%'},
  { value: '2', label: '2%'},
  { value: '3', label: '3%'},
  { value: '4', label: '4%'},
  { value: '5', label: '5%'},
  { value: '6', label: '6%'},
  { value: '7', label: '7%'},
  { value: '8', label: '8%'},
  { value: '9', label: '9%'},
  { value: '10', label: '10%'},
  { value: '11', label: '11%'},
  { value: '12', label: '12%'},
  { value: '13', label: '13%'},
  { value: '14', label: '14%'},
  { value: '15', label: '15%'},
  { value: '16', label: '16%'},
  { value: '17', label: '17%'},
  { value: '18', label: '18%'},
  { value: '19', label: '19%'},
  { value: '20', label: '20%'},
];

export const Locations = [
  { value: '', label: 'Select Country' },
  {value: 'USA', label: 'USA', states: [
    { value: '', label: 'Select State' },
    {value: 'Alabama', label: 'Alabama', regions: [
      {value: 'Madison County', label: 'Madison County'},
      {value: 'Montgomery County', label: 'Montgomery County'},
      {value: 'Dale County', label: 'Dale County'},
      {value: 'Calhoun County', label: 'Calhoun County'},
      {value: 'Mobile County', label: 'Mobile County'},
    ]},
    {value: 'Alaska', label: 'Alaska', regions: [
      {value: 'Anchorage Municipality', label: 'Anchorage Municipality'},
      {value: 'Fairbanks North Star Borough', label: 'Fairbanks North Star Borough'},
    ]},
    {value: 'Arizona', label: 'Arizona', regions: [
      {value: 'Pima County', label: 'Pima County'},
      {value: 'Maricopa County', label: 'Maricopa County'},
      {value: 'Cochise County', label: 'Cochise County'},
      {value: 'Yuma County', label: 'Yuma County'},
    ]},
    {value: 'Arkansas', label: 'Arkansas', regions: [
      {value: 'Pulaski County', label: 'Pulaski County'},
      {value: 'Ouachita County', label: 'Ouachita County'},
    ]},
    {value: 'California', label: 'California', regions: [
      {value: 'San Diego County', label: 'San Diego County'},
      {value: 'Kern County', label: 'Kern County'},
      {value: 'Ventura County', label: 'Ventura County'},
      {value: 'San Bernardino County', label: 'San Bernardino County'},
      {value: 'Monterey County', label: 'Monterey County'},
      {value: 'Solano County', label: 'Solano County'},
      {value: 'Los Angeles County', label: 'Los Angeles County'},
      {value: 'Riverside County', label: 'Riverside County'},
      {value: 'Kings County', label: 'Kings County'},
      {value: 'Yuba County', label: 'Yuba County'},
      {value: 'Santa Clara County', label: 'Santa Clara County'},
      {value: 'Sacramento County', label: 'Sacramento County'},
      {value: 'Yolo County', label: 'Yolo County'},
      {value: 'Orange County', label: 'Orange County'},
      {value: 'Santa Barbara County', label: 'Santa Barbara County'},
    ]},
    {value: 'Colorado', label: 'Colorado', regions: [
      {value: 'El Paso County', label: 'El Paso County'},
      {value: 'Arapahoe County', label: 'Arapahoe County'},
      {value: 'Adams County', label: 'Adams County'},
    ]},
    {value: 'Connecticut', label: 'Connecticut', regions: [
      {value: 'New London County', label: 'New London County'},
      {value: 'Fairfield County', label: 'Fairfield County'},
      {value: 'Hartford County', label: 'Hartford County'},
    ]},
    {value: 'Delaware', label: 'Delaware', regions: [
      {value: 'Kent County', label: 'Kent County'},
    ]},
    {value: 'District of Columbia', label: 'District of Columbia', regions: [
      {value: 'District of Columbia - District of Columbia', label: 'District of Columbia'},
    ]},
    {value: 'Florida', label: 'Florida', regions: [
      {value: 'Eglin AFB', label: 'Eglin AFB'},
      {value: 'Okaloosa County', label: 'Okaloosa County'},
      {value: 'Duval County', label: 'Duval County'},
      {value: 'Hillsborough County', label: 'Hillsborough County'},
      {value: 'Escambia County', label: 'Escambia County'},
      {value: 'Bay County', label: 'Bay County'},
      {value: 'Brevard County', label: 'Brevard County'},
      {value: 'Miami-Dade County', label: 'Miami-Dade County'},
      {value: 'Orange County', label: 'Orange County'},
      {value: 'Pinellas County', label: 'Pinellas County'},
      {value: 'Broward County', label: 'Broward County'},
    ]},
    {value: 'Georgia', label: 'Georgia', regions: [
      {value: 'Cobb County', label: 'Cobb County'},
      {value: 'Houston County', label: 'Houston County'},
      {value: 'Chatham County', label: 'Chatham County'},
      {value: 'Fulton County', label: 'Fulton County'},
      {value: 'Richmond County', label: 'Richmond County'},
      {value: 'Chattahoochee County', label: 'Chattahoochee County'},
      {value: 'Liberty County', label: 'Liberty County'},
      {value: 'Muscogee County', label: 'Muscogee County'},
      {value: 'Camden County', label: 'Camden County'},
      {value: 'Lowndes County', label: 'Lowndes County'},
    ]},
    {value: 'Hawaii', label: 'Hawaii', regions: [
      {value: 'Honolulu County', label: 'Honolulu County'},
    ]},
    {value: 'Idaho', label: 'Idaho', regions: [
      {value: 'Elmore County', label: 'Elmore County'},
    ]},
    {value: 'Illinois', label: 'Illinois', regions: [
      {value: 'St. Clair County', label: 'St. Clair County'},
      {value: 'Lake County', label: 'Lake County'},
      {value: 'Rock Island County', label: 'Rock Island County'},
      {value: 'Cook County', label: 'Cook County'},
      {value: 'DuPage County', label: 'DuPage County'},
      {value: 'Winnebago County', label: 'Winnebago County'},
      {value: 'Pulaski County', label: 'Pulaski County'},
      {value: 'Peoria County', label: 'Peoria County'},
    ]},
    {value: 'Indiana', label: 'Indiana', regions: [
      {value: 'Marion County', label: 'Marion County'},
      {value: 'Martin County', label: 'Martin County'},
      {value: 'St. Joseph County', label: 'St. Joseph County'},
      {value: 'Allen County', label: 'Allen County'},
    ]},
    {value: 'Iowa', label: 'Iowa', regions: [
      {value: 'Polk County', label: 'Polk County'},
      {value: 'Linn County', label: 'Linn County'},
    ]},
    {value: 'Kansas', label: 'Kansas', regions: [
      {value: 'Geary County', label: 'Geary County'},
      {value: 'Leavenworth County', label: 'Leavenworth County'},
      {value: 'Sedgwick County', label: 'Sedgwick County'},
    ]},
    {value: 'Kentucky', label: 'Kentucky', regions: [
      {value: 'Christian County', label: 'Christian County'},
      {value: 'Hardin County', label: 'Hardin County'},
      {value: 'Jefferson County', label: 'Jefferson County'},
      {value: 'Fayette County', label: 'Fayette County'},
      {value: 'Madison County', label: 'Madison County'},
    ]},
    {value: 'Louisiana', label: 'Louisiana', regions: [
      {value: 'Vernon Parish', label: 'Vernon Parish'},
      {value: 'Bossier Parish', label: 'Bossier Parish'},
      {value: 'Orleans Parish', label: 'Orleans Parish'},
    ]},
    {value: 'Maine', label: 'Maine', regions: [
      {value: 'York County', label: 'York County'},
      {value: 'Sagadahoc County', label: 'Sagadahoc County'},
      {value: 'Cumberland County', label: 'Cumberland County'},
    ]},
    {value: 'Maryland', label: 'Maryland', regions: [
      {value: 'D.C. Area', label: 'D.C. Area'},
      {value: 'Anne Arundel County', label: 'Anne Arundel County'},
      {value: 'St. Mary’s County', label: 'St. Mary’s County'},
      {value: 'Harford County', label: 'Harford County'},
      // {value: 'Montgomery County', label: 'Montgomery County'},//D.C. Area
      // {value: 'Prince George’s County', label: 'Prince George’s County'},//D.C. Area
      // {value: 'Frederick County', label: 'Frederick County'},//D.C. Area
      // {value: 'Charles County', label: 'Charles County'},//D.C. Area
      {value: 'Howard County', label: 'Howard County'},
      {value: 'Baltimore City', label: 'Baltimore City'},
      {value: 'Baltimore County', label: 'Baltimore County'},
      {value: 'Queen Anne’s County', label: 'Queen Anne’s County'},
    ]},
    {value: 'Massachusetts', label: 'Massachusetts', regions: [
      {value: 'Middlesex County', label: 'Middlesex County'},
      {value: 'Essex County', label: 'Essex County'},
      {value: 'Bristol County', label: 'Bristol County'},
      {value: 'Norfolk County', label: 'Norfolk County'},
      {value: 'Suffolk County', label: 'Suffolk County'},
      {value: 'Berkshire County', label: 'Berkshire County'},
      {value: 'Plymouth County', label: 'Plymouth County'},
      {value: 'Hampden County', label: 'Hampden County'},
    ]},
    {value: 'Michigan', label: 'Michigan', regions: [
      {value: 'Macomb County', label: 'Macomb County'},
    ]},
    {value: 'Minnesota', label: 'Minnesota', regions: [
      {value: 'Hennepin County', label: 'Hennepin County'},
      {value: 'Anoka County', label: 'Anoka County'},
    ]},
    {value: 'Mississippi', label: 'Mississippi', regions: [
      {value: 'Harrison County', label: 'Harrison County'},
      {value: 'Jackson County', label: 'Jackson County'},
      {value: 'Madison County', label: 'Madison County'},
      {value: 'Warren County', label: 'Warren County'},
    ]},
    {value: 'Missouri', label: 'Missouri', regions: [
      {value: 'Pulaski County', label: 'Pulaski County'},
      {value: 'Johnson County', label: 'Johnson County'},
      {value: 'St. Louis County', label: 'St. Louis County'},
      {value: 'Jackson County', label: 'Jackson County'},
      {value: 'St. Louis City', label: 'St. Louis City'},
    ]},
    {value: 'Montana', label: 'Montana', regions: [
      {value: 'Cascade County', label: 'Cascade County'},
    ]},
    {value: 'Nebraska', label: 'Nebraska', regions: [
      {value: 'Sarpy County', label: 'Sarpy County'},
    ]},
    {value: 'Nevada', label: 'Nevada', regions: [
      {value: 'Clark County', label: 'Clark County'},
      {value: 'Washoe County', label: 'Washoe County'},
    ]},
    {value: 'New Hampshire', label: 'New Hampshire', regions: [
      {value: 'Hillsborough County', label: 'Hillsborough County'},
    ]},
    {value: 'New Jersey', label: 'New Jersey', regions: [
      {value: 'Burlington County', label: 'Burlington County'},
      {value: 'Morris County', label: 'Morris County'},
      {value: 'Ocean County', label: 'Ocean County'},
      {value: 'Essex County', label: 'Essex County'},
      {value: 'Somerset County', label: 'Somerset County'},
      {value: 'Passaic County', label: 'Passaic County'},
      {value: 'Monmouth County', label: 'Monmouth County'},
      {value: 'Camden County', label: 'Camden County'},
    ]},
    {value: 'New Mexico', label: 'New Mexico', regions: [
      {value: 'Bernalillo County', label: 'Bernalillo County'},
      {value: 'Curry County', label: 'Curry County'},
      {value: 'Otero County', label: 'Otero County'},
      {value: 'Dona Ana County', label: 'Dona Ana County'},
    ]},
    {value: 'New York', label: 'New York', regions: [
      {value: 'Jefferson County', label: 'Jefferson County'},
      {value: 'Orange County', label: 'Orange County'},
      {value: 'Nassau County', label: 'Nassau County'},
      {value: 'Onondaga County', label: 'Onondaga County'},
      {value: 'Monroe County', label: 'Monroe County'},
      {value: 'Tioga County', label: 'Tioga County'},
      {value: 'Suffolk County', label: 'Suffolk County'},
      {value: 'New York County', label: 'New York County'},
      {value: 'Erie County', label: 'Erie County'},
      {value: 'Oneida County', label: 'Oneida County'},
    ]},
    {value: 'North Carolina', label: 'North Carolina', regions: [
      {value: 'Cumberland County', label: 'Cumberland County'},
      {value: 'Onslow County', label: 'Onslow County'},
      {value: 'Craven County', label: 'Craven County'},
      {value: 'Wayne County', label: 'Wayne County'},
      {value: 'Mecklenburg County', label: 'Mecklenburg County'},
    ]},
    {value: 'North Dakota', label: 'North Dakota', regions: [
      {value: 'Ward County', label: 'Ward County'},
    ]},
    {value: 'Ohio', label: 'Ohio', regions: [
      {value: 'Greene County', label: 'Greene County'},
      {value: 'Franlkin County', label: 'Franlkin County'},
      {value: 'Hamilton County', label: 'Hamilton County'},
      {value: 'Montgomery County', label: 'Montgomery County'},
      {value: 'Summit County', label: 'Summit County'},
    ]},
    {value: 'Oklahoma', label: 'Oklahoma', regions: [
      {value: 'Oklahoma County', label: 'Oklahoma County'},
      {value: 'Comanche County', label: 'Comanche County'},
      {value: 'Tulsa County', label: 'Tulsa County'},
    ]},
    {value: 'Oregon', label: 'Oregon', regions: [
      {value: 'Multnomah County', label: 'Multnomah County'},
      {value: 'Umatilla County', label: 'Umatilla County'},
    ]},
    {value: 'Pennsylvania', label: 'Pennsylvania', regions: [
      {value: 'Philadelphia County', label: 'Philadelphia County'},
      {value: 'Cumberland County', label: 'Cumberland County'},
      {value: 'York County', label: 'York County'},
      {value: 'Allegheny County', label: 'Allegheny County'},
      {value: 'Monroe County', label: 'Monroe County'},
      {value: 'Chester County', label: 'Chester County'},
      {value: 'Delaware County', label: 'Delaware County'},
      {value: 'Bucks County', label: 'Bucks County'},
      {value: 'Montgomery County', label: 'Montgomery County'},
      {value: 'Cambria County', label: 'Cambria County'},
      {value: 'Lackawanna County', label: 'Lackawanna County'},
    ]},
    {value: 'Rhode Island', label: 'Rhode Island', regions: [
      {value: 'Newport County', label: 'Newport County'},
    ]},
    {value: 'South Carolina', label: 'South Carolina', regions: [
      {value: 'Richland County', label: 'Richland County'},
      {value: 'Charleston County', label: 'Charleston County'},
      {value: 'Beaufort County', label: 'Beaufort County'},
      {value: 'Sumter County', label: 'Sumter County'},
      {value: 'Berkeley County', label: 'Berkeley County'},
    ]},
    // {value: 'South Dakota', label: 'South Dakota'},
    {value: 'Tennessee', label: 'Tennessee', regions: [
      {value: 'Shelby County', label: 'Shelby County'},
      {value: 'Davidson County', label: 'Davidson County'},
      {value: 'Coffee County', label: 'Coffee County'},
      {value: 'Sullivan County', label: 'Sullivan County'},
    ]},
    {value: 'Texas', label: 'Texas', regions: [
      {value: 'Bexar County', label: 'Bexar County'},
      {value: 'Bell County', label: 'Bell County'},
      {value: 'El Paso County', label: 'El Paso County'},
      {value: 'Tarrant County', label: 'Tarrant County'},
      {value: 'Nueces County', label: 'Nueces County'},
      {value: 'Wichita County', label: 'Wichita County'},
      {value: 'Taylor County', label: 'Taylor County'},
      {value: 'Harris County', label: 'Harris County'},
      {value: 'Dallas County', label: 'Dallas County'},
      {value: 'Potter County', label: 'Potter County'},
      {value: 'Hunt County', label: 'Hunt County'},
      {value: 'Collin County', label: 'Collin County'},
    ]},
    {value: 'Utah', label: 'Utah', regions: [
      {value: 'Davis County', label: 'Davis County'},
      {value: 'Salt Lake County', label: 'Salt Lake County'},
    ]},
    // {value: 'Vermont', label: 'Vermont'},
    {value: 'Virginia', label: 'Virginia', regions: [
      {value: 'Hampton Roads', label: 'Hampton Roads Area'},
      {value: 'D.C. Area', label: 'D.C. Area'},
      // {value: 'Norfolk City', label: 'Norfolk City'},//Hampton Roads Area
      // {value: 'Fairfax County', label: 'Fairfax County'},//D.C. Area
      // {value: 'Arlington County', label: 'Arlington County'},//D.C. Area
      // {value: 'Virginia Beach City', label: 'Virginia Beach City'},//Hampton Roads Area
      // {value: 'Portsmouth City', label: 'Portsmouth City'},//Hampton Roads Area
      {value: 'Accomack County', label: 'Accomack County'},
      {value: 'Prince George County', label: 'Prince George County'},
      // {value: 'Newport News City', label: 'Newport News City'},//Hampton Roads Area
      // {value: 'York County', label: 'York County'},//Hampton Roads Area
      // {value: 'Prince William County', label: 'Prince William County'},//D.C. Area
      // {value: 'Alexandria City', label: 'Alexandria City'},//D.C. Area
      // {value: 'Loudoun County', label: 'Loudoun County'},//D.C. Area
      {value: 'King George County', label: 'King George County'},
    ]},
    {value: 'Washington', label: 'Washington', regions: [
      {value: 'Pierce County', label: 'Pierce County'},
      {value: 'Kitsap County', label: 'Kitsap County'},
      {value: 'Island County', label: 'Island County'},
      {value: 'Spokane County', label: 'Spokane County'},
      {value: 'King County', label: 'King County'},
      {value: 'Klickitat County', label: 'Klickitat County'},
    ]},
    // {value: 'West Virginia', label: 'West Virginia'},
    {value: 'Wisconsin', label: 'Wisconsin', regions: [
      {value: 'Winnebago County', label: 'Winnebago County'},
    ]},
    {value: 'Wyoming', label: 'Wyoming', regions: [
      {value: 'Laramie County', label: 'Laramie County'},
    ]}
  ]},
  { value: 'Australia', label: 'Australia' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Guam', label: 'Guam' },
  { value: 'Hungary', label: 'Hungary'},
  { value: 'Italy', label: 'Italy' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Korea', label: 'Korea' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Puerto Rico', label: 'Puerto Rico' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'United Kingdom', label: 'United Kingdom' },
  ];

// export const Industries = [
//   { value: '', label: 'Select Job Type:'},
//   { value: 'Aerospace/Aviation', label: 'Aerospace/Aviation'},
//   { value: 'Engineering', label: 'Engineering'},
//   // { value: 'Engineering (Chemical)', label: 'Engineering (Chemical)'},
//   // { value: 'Engineering (Civil)', label: 'Engineering (Civil)'},
//   // { value: 'Engineering (Electrical)', label: 'Engineering (Electrical)'},
//   // { value: 'Engineering (Mechanical)', label: 'Engineering (Mechanical)'},
//   // { value: 'Engineering (Systems)', label: 'Engineering (Systems)'},
//   { value: 'Instructional Design', label: 'Instructional Design'},
//   { value: 'Intelligence', label: 'Intelligence'},
//   { value: 'Information Technology', label: 'Information Technology'},
//   // { value: 'IT (Data Science)', label: 'IT (Data Science)'},
//   // { value: 'IT (Database)', label: 'IT (Database)'},
//   // { value: 'IT (Hardware)', label: 'IT (Hardware)'},
//   // { value: 'IT (Quality Assurance)', label: 'IT (Quality Assurance)'},
//   // { value: 'IT (Security)', label: 'IT (Security)'},
//   // { value: 'IT (Software Development)', label: 'IT (Software Development)'},
//   // { value: 'IT (Support)', label: 'IT (Support)'},
//   { value: 'Management', label: 'Management'},
//   // { value: 'Science (Cognitive)', label: 'Science (Cognitive)'},
//   // { value: 'Science (Mathematics)', label: 'Science (Mathematics)'},
//   // { value: 'Science (Nuclear)', label: 'Science (Nuclear)'},
//   // { value: 'Science (Optics)', label: 'Science (Optics)'},
//   { value: 'Physics', label: 'Physics'},
//   // { value: 'Science (Physics)', label: 'Science (Physics)'},
//   { value: 'Test & Evaluation', label: 'Test & Evaluation'},
//   // { value: 'Testing (HIL Design)', label: 'Testing (HIL Design)'},
//   // { value: 'Testing (HIL Operation)', label: 'Testing (HIL Operation)'},
//   // { value: 'Testing (M&S)', label: 'Testing (M&S)'},
//   { value: 'Support', label: 'Support'},
// ];

// export const Industries = [
//   { value: '', label: 'Select Industry:'},
//   { value: 'Aerospace/Aviation', label: 'Aerospace/Aviation'},
//   { value: 'Engineering', label: 'Engineering'},
//   { value: 'Instructional Design', label: 'Instructional Design'},
//   { value: 'Intelligence', label: 'Intelligence'},
//   { value: 'Information Technology', label: 'Information Technology'},
//   { value: 'Management', label: 'Management'},
//   { value: 'Sciences', label: 'Sciences'},
//   { value: 'Testing', label: 'Testing'},
// ];

// export const Industries = [
//   { value: '', label: 'Select Job Type:'},
//   { value: 'Aerospace/Aviation', label: 'Aerospace/Aviation'},
//   { value: 'Intelligence', label: 'Intelligence'},
//   { value: 'Test/Evaluation', label: 'Test/Evaluatoin'},
//   // { value: 'Custom', label: 'Custom'},

//   { value: 'Management/Administration', label: 'Management/Administration'},
//   { value: 'Finance', label: 'Finance'},
//   { value: 'Hospitality', label: 'Hospitality'},
  
//   { value: 'Information Technology', label: 'Information Technology'},
  
//   { value: 'Engineering/Science', label: 'Engineering/Science'},
//   { value: 'Mathematics', label: 'Mathematics'},
//   { value: 'Architecture/Manufacturing', label: 'Architecture/Manufacturing'},
//   { value: 'Logistics', label: 'Logistics'},
  
//   { value: 'Healthcare', label: 'Healthcare'},
  
//   { value: 'Education/Training', label: 'Education/Training'},
// ];

export const Clearances = [
  { value: '', label: 'Select Clearance Level:'},
  { value: 'No Clearance', label: 'No Clearance Required'},
  { value: 'Confidential', label: 'Confidential'},
  { value: 'Secret', label: 'Secret'},
  { value: 'Top Secret', label: 'Top Secret'},
  { value: 'Top Secret/SCI', label: 'Top Secret/SCI'},
];

export const Polygraphs = [
  { value: '', label: 'Select Polygraph Level:'},
  { value: ' ', label: 'No Polygraph Required'},
  { value: '/Poly', label: 'Polygraph'},
  { value: '/CI Poly', label: 'CI Polygraph'},
  { value: '/FS Poly', label: 'Full Scope Polygraph'},
];

export const Sorters = [
  // { value: '', label: 'Sort Results By:'},
  { value: 'Salary', label: 'Maximum Salary'},
  { value: 'Recent', label: 'Recently Added'},
  { value: 'Retirement', label: '401k Matching'},
  { value: 'Time Off', label: 'Paid Time Off'},
];